// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkcwyzwgojpnvlessmjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrY3d5endnb2pwbnZsZXNzbWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTMyMzgsImV4cCI6MjA2MzMyOTIzOH0.0Wh_sdIvIjQ8I-g1Ppq-cUjl3LuvdDoWSKj8sP61Pdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);